---
title: "Tarea_5 - C21380 - FabianBrenesThomas_C24067 - AnthonyJimenezNavarro"
author: 
  - Estudiantes
  - Fabián Brenes Thomas - C21380
  - Anthony Mauricio Jiménez Navarro - C24067
date: "2024-07-03"
output: 
  rmdformats::downcute:
    default_style: "dark"
    downcute_theme: "chaos"
---

```{r, warning=FALSE, message=FALSE, echo=FALSE}
# Preparativos
# Cargar las configuraciones iniciales
source("cod/r/setup.R")
```

```{r, echo=FALSE}
# Se carga la base del archivo .xlsx
Datos.original <- read_excel("data/Datos.xlsx")
```

```{r, echo=FALSE}
# Tratamiento de los datos

# Se eliminan las entradas que cuentan con valores NA, ya que las entradas con NA unicamente corresponden a titulos de los apartados, no resulta inadecuado. eliminar estos
Datos <- Datos.original %>% drop_na()

# Se transforman los datos a un formato long, esto para llevar a cabo la transposicion adecuada para estudiar los datos.
Datos <- Datos %>%
  pivot_longer(cols = -`Componente demográfico`, names_to = "Year", values_to = "Value")

# Los datos previamente convertidos a un formato long ahora se pueden pasar a un formate wide, de forma que resulta mas adecuado llevar a cabo el estudio.
Datos <- Datos %>%
  pivot_wider(names_from = `Componente demográfico`, values_from = "Value")

# Se convierten todas las variables a numeric
Datos <- as.data.frame(sapply(Datos, as.numeric))
```

```{css, echo=FALSE}
.break .nav-tabs {
  display: grid;
  grid-template-columns: repeat(3, 1fr):
  text-align: center;
}

.break .nav-tabs:before,
.break .nav-tabs:after {
  content: unset;
}
```

# Analisis exploratorio de datos {.tabset .break}

```{r, echo=FALSE}
summary(Datos)
cor.matrix <- cor(Datos)
corrplot(cor.matrix, "circle", tl.cex = 0.5)
```

## Grafico 1
```{r, echo=FALSE}
grafico1 <- ggplot(Datos, aes(x = Year, y = Reproduccion_bruta)) +
  geom_line() +
  geom_point() +
  labs(title = "Reproducción Bruta por Año",
       x = "Año",
       y = "Reproducción Bruta") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
p1.dinamico <- ggplotly(grafico1)

p1.dinamico
```

## Grafico 2
```{r}
grafico2 <- ggplot(Datos, aes(x = Year, y = `Tasa de crecimiento natural (por cien habitantes)`)) +
  geom_line() +
  geom_point() +
  labs(title = "Tasa de crecimiento natural por Año",
       x = "Año",
       y = "Tasa de crecimiento natural") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
p2.dinamico <- ggplotly(grafico2)

p2.dinamico
```

## Grafico 3
```{r}
grafico3 <- ggplot(Datos, aes(x = Year, y = `General (por mil habitantes)`)) +
  geom_line() +
  geom_point() +
  labs(title = "Mortalidad general por mil habitantes por Año",
       x = "Año",
       y = "Mortalidad general por mil habitantes") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

p3.dinamico <- ggplotly(grafico3)

p3.dinamico
```

##Grafico 4
```{r}
grafico4 <- ggplot(Datos, aes(x = Year, y = Poblacion_total)) +
  geom_line() +
  geom_point() +
  labs(title = "Poblacion total por Año",
       x = "Año",
       y = "Poblacion total") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
p4.dinamico <- ggplotly(grafico4)

p4.dinamico
```

##Grafico 5
```{r}
grafico5 <- ggplot(Datos, aes(x = Year, y = `Tasa de nupcialidad (por mil habitantes)`)) +
  geom_line() +
  geom_point() +
  labs(title = "Tasa de nupcialidad por mil habitantes por Año",
       x = "Año",
       y = "Nupcialidad por mil habitantes") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
p5.dinamico <- ggplotly(grafico5)

p5.dinamico
```

##Grafico resumen
```{r}
grafico.combinado <- ggplot(Datos) +
  geom_line(aes(x = Year, y = Reproduccion_bruta, color = "Reproducción Bruta")) +
  geom_point(aes(x = Year, y = Reproduccion_bruta, color = "Reproducción Bruta")) +
  geom_line(aes(x = Year, y = `Tasa de crecimiento natural (por cien habitantes)`, color = "Tasa de crecimiento natural")) +
  geom_point(aes(x = Year, y = `Tasa de crecimiento natural (por cien habitantes)`, color = "Tasa de crecimiento natural")) +
  geom_line(aes(x = Year, y = `General (por mil habitantes)`, color = "Mortalidad general")) +
  geom_point(aes(x = Year, y = `General (por mil habitantes)`, color = "Mortalidad general")) +
  geom_line(aes(x = Year, y = `Tasa de nupcialidad (por mil habitantes)`, color = "Tasa de nupcialidad")) +
  geom_point(aes(x = Year, y = `Tasa de nupcialidad (por mil habitantes)`, color = "Tasa de nupcialidad")) +
  labs(title = "Diferentes Métricas por Año",
       x = "Año",
       y = "Valor",
       color = "Métricas") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

grafico.combinado.dinamico <- ggplotly(grafico.combinado)
grafico.combinado.dinamico
```
## {-}

# Graficos dinamicos

```{r}
grafico1 <- ggplot(Datos, aes(x = Year, y = Reproduccion_bruta)) +
  geom_line() +
  geom_point() +
  labs(title = "Reproducción Bruta por Año",
       x = "Año",
       y = "Reproducción Bruta") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
p1_dinamico <- ggplotly(grafico1)

grafico2 <- ggplot(Datos, aes(x = Year, y = `Tasa de crecimiento natural (por cien habitantes)`)) +
  geom_line() +
  geom_point() +
  labs(title = "Tasa de crecimiento natural por Año",
       x = "Año",
       y = "Tasa de crecimiento natural") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
p2_dinamico <- ggplotly(grafico2)

grafico3 <- ggplot(Datos, aes(x = Year, y = `General (por mil habitantes)`)) +
  geom_line() +
  geom_point() +
  labs(title = "Mortalidad general por mil habitantes por Año",
       x = "Año",
       y = "Mortalidad general por mil habitantes") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
p3_dinamico <- ggplotly(grafico3)

grafico4 <- ggplot(Datos, aes(x = Year, y = Poblacion_total)) +
  geom_line() +
  geom_point() +
  labs(title = "Poblacion total por Año",
       x = "Año",
       y = "Poblacion total") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
p4_dinamico <- ggplotly(grafico4)

grafico5 <- ggplot(Datos, aes(x = Year, y = `Tasa de nupcialidad (por mil habitantes)`)) +
  geom_line() +
  geom_point() +
  labs(title = "Tasa de nupcialidad por mil habitantes por Año",
       x = "Año",
       y = "Nupcialidad por mil habitantes") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
p5_dinamico <- ggplotly(grafico5)
```

```{r}
p1_dinamico
p2_dinamico
p3_dinamico
p4_dinamico
p5_dinamico
```

# Grafico resumen

```{r}
grafico_combinado <- ggplot(Datos) +
  geom_line(aes(x = Year, y = Reproduccion_bruta, color = "Reproducción Bruta")) +
  geom_point(aes(x = Year, y = Reproduccion_bruta, color = "Reproducción Bruta")) +
  geom_line(aes(x = Year, y = `Tasa de crecimiento natural (por cien habitantes)`, color = "Tasa de crecimiento natural")) +
  geom_point(aes(x = Year, y = `Tasa de crecimiento natural (por cien habitantes)`, color = "Tasa de crecimiento natural")) +
  geom_line(aes(x = Year, y = `General (por mil habitantes)`, color = "Mortalidad general")) +
  geom_point(aes(x = Year, y = `General (por mil habitantes)`, color = "Mortalidad general")) +
  geom_line(aes(x = Year, y = `Tasa de nupcialidad (por mil habitantes)`, color = "Tasa de nupcialidad")) +
  geom_point(aes(x = Year, y = `Tasa de nupcialidad (por mil habitantes)`, color = "Tasa de nupcialidad")) +
  labs(title = "Diferentes Métricas por Año",
       x = "Año",
       y = "Valor",
       color = "Métricas") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

grafico_combinado_dinamico <- ggplotly(grafico_combinado)
grafico_combinado_dinamico
```

